title: Crotal
subtitle: Do one thing, do it well.
author: John Doe
simple_search: http://google.com/search
description: A static site generator which is written in Python, easy to use, and free to all. Start a blog right now using Crotal!
url: http://your-url-here.com # url of your site
root_path: / # If publishing to a subdirectory as in http://site.com/project set 'root: /project/'

navbar: [Home: '', Archives: archives, About: about]

email: john@doe.om

deploy_default: rsync
ip: root@8.8.8.8
remote_dir: /var/www/html

permalink: :title

theme: hueman

paginate:  5         # Posts per page on the blog index
recent_posts: 5       # Posts in the sidebar Recent Posts section

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in "${THEME_FOLDER}/public/_includes/asides/" and add them to the list like "custom/asides/custom_aside_name.html"
default_asides: [asides/recent_posts.html, asides/categories.html, asides/archives.html, asides/tags.html]

mathjax: true

# Disqus Comments
disqus_short_name:

facebook_id:
twitter_id:
google_plus_id:
github_id:
weibo_id:
