title: Crotal
subtitle: A static site generator written in Python.
author: user
simple_search: http://google.com/search
keywords:
description: A static site generator which is written in Python, super fast, easy to use, and free to all.Start a blog right now using Crotal!
author_avatar: /images/avatar.gif  # 200*200 is prefered.
self_description: Hello World! I'm <b>User</b>. Change this text in <code>_config.yml</code> <code>-> self_description</code>.

navbar: [Home: /, Archives: /archives, Categories: /categories, Tags: /tags, About: /about, RSS: /rss.xml]

email:

deploy_default: rsync
ip: root@8.8.8.8
remote_dir: /var/www/html

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root_url: example.com/project
permalink: blog/:year/:month/:day/:title

theme: riverside

paginate: 5          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read More"  # "Continue reading" link text at the bottom of excerpted articles

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/about.html, asides/recent_post.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
#
# Weibo
weibo_uid:

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_count: 5
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

comment_system: disqus

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: true

# Duoshuo Comments
duoshuo_short_name:

# Google Analytics
google_analytics_tracking_id:

# Clicky
clicky_tracking_id:

# Woopra
woopra_tracking_site:

# Facebook Like
facebook_like: false

# Popular Posts
popular_posts_count: 5
